version: "3.9"

services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-payment-db
    restart: always
    command: --default-authentication-plugin=mysql_native_password --bind-address=0.0.0.0
    environment:
      MYSQL_ROOT_PASSWORD: "Pranav@2005"
      MYSQL_DATABASE: Payment_db
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - payment-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 10s
      retries: 30

  payment-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: payment-service
    restart: always

    depends_on:
      mysql-db:
        condition: service_healthy

    environment:
      # ==== MYSQL ====
      SPRING_DATASOURCE_URL: "jdbc:mysql://mysql-db:3306/Payment_db?allowPublicKeyRetrieval=true&useSSL=false&connectTimeout=60000&socketTimeout=60000"
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: "Pranav@2005"

      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: true
      SPRING_JPA_HIBERNATE_DIALECT: org.hibernate.dialect.MySQL8Dialect

      # ==== EUREKA ====
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://eureka-server:8761/eureka/"
      EUREKA_CLIENT_REGISTER_WITH_EUREKA: true
      EUREKA_CLIENT_FETCH_REGISTRY: true

      # ==== KAFKA ====
      SPRING_KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"

      # ==== RAZORPAY KEYS ====
      RAZORPAY_KEY_ID: "rzp_test_RkKXQKUjFhu4mv"
      RAZORPAY_KEY_SECRET: "T5Xghky6s22AAh23Ee1cgQyv"

      # ==== SERVER PORT ====
      SERVER_PORT: 8083

    ports:
      - "8083:8083"

    networks:

      - payment-net
      - app-net

volumes:
  mysql_data:

networks:

  payment-net:

  app-net:
    external: true
